/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as ApiPublicCycleRouteImport } from './routes/api/public/cycle'
import { Route as ApiPublicProofDotjsonRouteImport } from './routes/api/public/proof[.]json'
import { Route as ApiPublicVerifyDotjsonRouteImport } from './routes/api/public/verify[.]json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCycleRoute = ApiPublicCycleRouteImport.update({
  id: '/api/public/cycle',
  path: '/api/public/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProofDotjsonRoute = ApiPublicProofDotjsonRouteImport.update({
  id: '/api/public/proof.json',
  path: '/api/public/proof.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVerifyDotjsonRoute = ApiPublicVerifyDotjsonRouteImport.update({
  id: '/api/public/verify.json',
  path: '/api/public/verify.json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proof': typeof ProofRoute
  '/api/public/cycle': typeof ApiPublicCycleRoute
  '/api/public/proof.json': typeof ApiPublicProofDotjsonRoute
  '/api/public/verify.json': typeof ApiPublicVerifyDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proof': typeof ProofRoute
  '/api/public/cycle': typeof ApiPublicCycleRoute
  '/api/public/proof.json': typeof ApiPublicProofDotjsonRoute
  '/api/public/verify.json': typeof ApiPublicVerifyDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proof': typeof ProofRoute
  '/api/public/cycle': typeof ApiPublicCycleRoute
  '/api/public/proof.json': typeof ApiPublicProofDotjsonRoute
  '/api/public/verify.json': typeof ApiPublicVerifyDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proof'
    | '/api/public/cycle'
    | '/api/public/proof.json'
    | '/api/public/verify.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/proof'
    | '/api/public/cycle'
    | '/api/public/proof.json'
    | '/api/public/verify.json'
  id:
    | '__root__'
    | '/'
    | '/proof'
    | '/api/public/cycle'
    | '/api/public/proof.json'
    | '/api/public/verify.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProofRoute: typeof ProofRoute
  ApiPublicCycleRoute: typeof ApiPublicCycleRoute
  ApiPublicProofDotjsonRoute: typeof ApiPublicProofDotjsonRoute
  ApiPublicVerifyDotjsonRoute: typeof ApiPublicVerifyDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cycle': {
      id: '/api/public/cycle'
      path: '/api/public/cycle'
      fullPath: '/api/public/cycle'
      preLoaderRoute: typeof ApiPublicCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proof.json': {
      id: '/api/public/proof.json'
      path: '/api/public/proof.json'
      fullPath: '/api/public/proof.json'
      preLoaderRoute: typeof ApiPublicProofDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify.json': {
      id: '/api/public/verify.json'
      path: '/api/public/verify.json'
      fullPath: '/api/public/verify.json'
      preLoaderRoute: typeof ApiPublicVerifyDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProofRoute: ProofRoute,
  ApiPublicCycleRoute: ApiPublicCycleRoute,
  ApiPublicProofDotjsonRoute: ApiPublicProofDotjsonRoute,
  ApiPublicVerifyDotjsonRoute: ApiPublicVerifyDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
